### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by jasonseminara** [LuisLithgow/BlackJack#1]
Before I OK this, can you list, in order, the many rules of the game? Like, how many states can the game be in and how do does the game progress? How do you declare a winner?

**Comment by LuisLithgow** [comment]
Ahh ok. After bouncing around and creating and deleting repos for the many
game ideas I was going to run I decided to go for something that I know is
doable within the time allowed and hard enough that has enough tough logic
to give me  a challenge.
I want to run a simple blackjack game, where there is no insurance, split,
betting, etc.
My plan is simple, have a start game button, which will then prompt the
user to hit(hitMe()), stand(stand()) or reset the game(resetGame()).

In regards to the tricky part of having an ace, I decided to maintain the
ace value as 11 for any card values that are less than 8 (soft hand) and
ace as 1 for any card values higher than 9 (hard hand).

Rules/approach:
1. dealButton will initialize startGame function and continue to execute
   playerHand function
2. playerHand function will automatically give you one card and then
   with each press of the dealButton will give you another card until player
   decides to stand or reset game.
3. An array of of suits and numbers will be created
4. In the shuffle() function looped randomly to assign the suit and
   number for each card randomly picked to playerHand()
5. While playerHand function is running, dealerHand will also be running
   but will be logged in the console
6. Function hitMe() and stand() will also check to see if the user
   chooses another random card
7. The resetGame() will have a reset button to for the user to choose if
   he or she want to ever start all over again
8. declareWinner function will run to check will hand is the winner with
   an if and else statemets within a loop
9. A message will appear on a div or an alert will pop up of the status
   of the match

Thank you,
Luis A. Lithgow
347-213-6088
